const ADD_PLAYLIST = 'ADD_PLAYLIST';
const ADD_NUMBER_OF_PAGES = 'ADD_NUMBER_OF_PAGES';
const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
const ADD_TOTAL_COUNT = 'ADD_TOTAL_COUNT';
const ADD_CURRENT_PAGE = 'ADD_CURRENT_PAGE';
const ADD_DATA_FOR_UNICUE_ITEMS = 'ADD_DATA_FOR_UNICUE_ITEMS';

export {
    ADD_PLAYLIST,
    ADD_NUMBER_OF_PAGES,
    SET_PAGE_SIZE,
    ADD_TOTAL_COUNT,
    ADD_CURRENT_PAGE,
    ADD_DATA_FOR_UNICUE_ITEMS
}