const ADD_PLAYLIST = 'ADD_PLAYLIST';
const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
const ADD_TOTAL_COUNT = 'ADD_TOTAL_COUNT';
const ADD_CURRENT_PAGE = 'ADD_CURRENT_PAGE';
const ADD_DATA_FOR_UNICUE_ITEMS = 'ADD_DATA_FOR_UNICUE_ITEMS';
const ADD_SELECT_VALUE = 'ADD_SELECT_VALUE';
const ADD_SELECT_SINGER_VALUE = 'ADD_SELECT_SINGER_VALUE';
const ADD_SELECT_GANRE_VALUE = 'ADD_SELECT_GANRE_VALUE';
const ADD_SELECT_YEAR_VALUE = 'ADD_SELECT_YEAR_VALUE';
const SORT_BY_SINGER = 'SORT_BY_SINGER';
const SORT_BY_SONG = 'SORT_BY_SONG';
const SORT_BY_GANRE = 'SORT_BY_GANRE';
const SORT_BY_YEAR = 'SORT_BY_YEAR';

export {
    ADD_PLAYLIST,
    SET_PAGE_SIZE,
    ADD_TOTAL_COUNT,
    ADD_CURRENT_PAGE,
    ADD_DATA_FOR_UNICUE_ITEMS,
    ADD_SELECT_VALUE,
    ADD_SELECT_SINGER_VALUE,
    ADD_SELECT_GANRE_VALUE,
    ADD_SELECT_YEAR_VALUE,
    SORT_BY_SINGER,
    SORT_BY_SONG,
    SORT_BY_GANRE,
    SORT_BY_YEAR
}